from __future__ import annotations

import argparse
from collections import defaultdict
from pathlib import Path


SOURCE_EXTENSIONS = {
    ".c",
    ".cc",
    ".cpp",
    ".cxx",
    ".h",
    ".hh",
    ".hpp",
    ".hxx",
    ".java",
    ".kt",
    ".py",
    ".rs",
    ".go",
    ".sh",
}

LISTING_LANGUAGES = {
    ".sh": "bash",
}

IGNORED_DIRS = {
    ".git",
    ".vscode",
    ".idea",
    "__pycache__",
    "build",
    "cmake-build-debug",
    "cmake-build-release",
    "dist",
    "out",
    "template",
    "tmp",
    "tools",
}


def tex_escape(text: str) -> str:
    replacements = {
        "\\": r"\textbackslash{}",
        "&": r"\&",
        "%": r"\%",
        "$": r"\$",
        "#": r"\#",
        "_": r"\_",
        "{": r"\{",
        "}": r"\}",
        "~": r"\textasciitilde{}",
        "^": r"\textasciicircum{}",
    }
    return "".join(replacements.get(ch, ch) for ch in text)


def is_ignored(path: Path, root: Path) -> bool:
    rel_parts = path.relative_to(root).parts
    return any(part in IGNORED_DIRS or part.startswith(".") for part in rel_parts[:-1])


def collect_sources(root: Path) -> list[Path]:
    sources: list[Path] = []
    for path in root.rglob("*"):
        if not path.is_file():
            continue
        if is_ignored(path, root):
            continue
        if path.suffix.lower() in SOURCE_EXTENSIONS:
            sources.append(path)
    return sorted(sources, key=lambda item: item.relative_to(root).as_posix().lower())


def write_generated(root: Path, output: Path, sources: list[Path]) -> None:
    grouped: dict[str, list[Path]] = defaultdict(list)
    for source in sources:
        rel = source.relative_to(root)
        section = rel.parts[0] if len(rel.parts) > 1 else "Root"
        grouped[section].append(source)

    lines = [
        "% Auto-generated by template/tools/generate_template_tex.py; do not edit directly.",
        "",
    ]

    for section in sorted(
        grouped, key=lambda name: (name.casefold() == "other", name.casefold())
    ):
        lines.append(rf"\section{{{tex_escape(section)}}}")
        for source in grouped[section]:
            rel = source.relative_to(root).as_posix()
            title = source.stem
            language = LISTING_LANGUAGES.get(source.suffix.lower())
            command = rf"\codefile[{language}]" if language else r"\codefile"
            lines.append(
                rf"{command}{{{tex_escape(title)}}}{{{tex_escape(rel)}}}{{{rel}}}"
            )
        lines.append("")

    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text("\n".join(lines), encoding="utf-8", newline="\n")


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Generate the LaTeX include file for the ICPC template."
    )
    parser.add_argument(
        "--root",
        type=Path,
        default=Path(__file__).resolve().parents[2],
        help="Repository root to scan.",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=Path("template/generated/code-listings.tex"),
        help="Generated TeX include path, relative to --root unless absolute.",
    )
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    root = args.root.resolve()
    output = args.output if args.output.is_absolute() else root / args.output
    sources = collect_sources(root)
    write_generated(root, output, sources)
    print(f"Generated {output.relative_to(root)} with {len(sources)} source file(s).")


if __name__ == "__main__":
    main()
